# Your Name or Company
title: Stephanie Cheung, PhD

# Description of your website. This is used for social sharing.
description: Stephanie Cheung's website

# Website URL
url: https://stephaniecheung.ca

# A brief blurb about yourself
content: Strategist, policymaker, advisor. I am a systems thinker with a biomedical engineering background and a research lens. I use a process mindset to develop elegant solutions for complex public policy issues.

# Add your social links
social:
  - platform: LinkedIn
    url: https://www.linkedin.com/in/stephanietcheung/
  - platform: ORCID
    url: https://orcid.org/0000-0001-7006-3160
  - platform: Email
    url: mailto:hello@stephaniecheung.ca

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni"
markdown: kramdown
sharing_image: share.jpg

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
