# Your Name or Company
title: Stephanie Cheung, PhD

# Description of your website. This is used for social sharing.
description: Stephanie Cheung's website

# Website URL
url: https://stephaniecheung.ca

# A brief blurb about yourself
content: Systems-thinking strategist and policymaker with a research lens. I use a process mindset to develop elegant solutions for complex issues.

# Add your social links
social:
  - platform: linkedin
    url: http://linkedin.com/in/stephanietcheung
  - platform: orcid
    url: https://orcid.org/0000-0001-7006-3160
  - platform: email
    url: mailto:hello@stephaniecheung.ca

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni"
markdown: kramdown
sharing_image: share.jpg

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
